/**
 * Cinema data with addresses, coordinates, and website links
 */

export interface Cinema {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  website?: string;
  district?: string;
}

export const CINEMAS_DATA: Record<string, Cinema[]> = {
  paris: [
    // Cinémas multiplexes
    {
      id: 'P0003',
      name: 'MK2 Bastille',
      address: '2-4 Boulevard Richard Lenoir, 75011 Paris',
      lat: 48.8525,
      lng: 2.3703,
      website: 'https://www.mk2.com/salles/mk2-bastille',
      district: '11e arrondissement',
    },
    {
      id: 'P0005',
      name: 'Pathé Wepler',
      address: '140 Boulevard de Clichy, 75018 Paris',
      lat: 48.8842,
      lng: 2.3331,
      website: 'https://www.cinemaspathegaumont.com/cinema/cinema-pathe-wepler',
      district: '18e arrondissement',
    },
    {
      id: 'P0006',
      name: 'MK2 Quai de Seine',
      address: '14 Quai de la Seine, 75019 Paris',
      lat: 48.8847,
      lng: 2.3656,
      website: 'https://www.mk2.com/salles/mk2-quai-de-seine',
      district: '19e arrondissement',
    },
    {
      id: 'P0009',
      name: 'Pathé Beaugrenelle',
      address: '7 Rue Linois, 75015 Paris',
      lat: 48.8506,
      lng: 2.2808,
      website: 'https://www.cinemaspathegaumont.com/cinema/cinema-pathe-beaugrenelle',
      district: '15e arrondissement',
    },
    // Cinémas indépendants
    {
      id: 'C0134',
      name: "L'Archipel",
      address: '17 Boulevard de Strasbourg, 75010 Paris',
      lat: 48.8706,
      lng: 2.3608,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/larchipel',
      district: '10e arrondissement',
    },
    {
      id: 'C0054',
      name: "L'Arlequin",
      address: '76 Rue de Rennes, 75006 Paris',
      lat: 48.8447,
      lng: 2.3331,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/larlequin',
      district: '6e arrondissement',
    },
    {
      id: 'C0009',
      name: 'Le Balzac',
      address: '1 Rue Balzac, 75008 Paris',
      lat: 48.8742,
      lng: 2.3003,
      website: 'https://www.cinemabalzac.com',
      district: '8e arrondissement',
    },
    {
      id: 'C0023',
      name: 'Le Brady',
      address: '39 Boulevard de Strasbourg, 75010 Paris',
      lat: 48.8708,
      lng: 2.3603,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/le-brady',
      district: '10e arrondissement',
    },
    {
      id: 'C0015',
      name: 'Christine Cinéma Club',
      address: '4 Rue Christine, 75006 Paris',
      lat: 48.8536,
      lng: 2.3408,
      website: 'https://www.pariscinemaclub.com/christine',
      district: '6e arrondissement',
    },
    {
      id: 'C0076',
      name: 'Cinéma du Panthéon',
      address: '13 Rue Victor Cousin, 75005 Paris',
      lat: 48.8481,
      lng: 2.3436,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/cinema-du-pantheon',
      district: '5e arrondissement',
    },
    {
      id: 'C0071',
      name: 'Écoles Cinéma Club',
      address: '23 Rue des Écoles, 75005 Paris',
      lat: 48.8503,
      lng: 2.3442,
      website: 'https://www.pariscinemaclub.com/ecoles',
      district: '5e arrondissement',
    },
    {
      id: 'C0005',
      name: "L'Entrepôt",
      address: '7-9 Rue Francis de Pressensé, 75014 Paris',
      lat: 48.8331,
      lng: 2.3203,
      website: 'https://www.cinemalentrepot.fr',
      district: '14e arrondissement',
    },
    {
      id: 'W7504',
      name: "L'Épée de bois",
      address: '100 Rue Mouffetard, 75005 Paris',
      lat: 48.8414,
      lng: 2.3469,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/lepee-de-bois',
      district: '5e arrondissement',
    },
    {
      id: 'C0147',
      name: "L'Escurial",
      address: '11 Boulevard de Port-Royal, 75013 Paris',
      lat: 48.8381,
      lng: 2.3456,
      website: 'https://www.dulaccinemas.com/cinema/2852/lescurial/portail',
      district: '13e arrondissement',
    },
    {
      id: 'C0072',
      name: 'Grand Action',
      address: '5 Rue des Écoles, 75005 Paris',
      lat: 48.8506,
      lng: 2.3447,
      website: 'https://www.legrandaction.com',
      district: '5e arrondissement',
    },
    {
      id: 'W7510',
      name: 'Le Louxor',
      address: '170 Boulevard de Magenta, 75010 Paris',
      lat: 48.8803,
      lng: 2.3508,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/le-louxor',
      district: '10e arrondissement',
    },
    {
      id: 'C0093',
      name: 'Lucernaire',
      address: '53 Rue Notre-Dame-des-Champs, 75006 Paris',
      lat: 48.8442,
      lng: 2.3336,
      website: 'https://www.lucernaire.fr',
      district: '6e arrondissement',
    },
    {
      id: 'C0013',
      name: 'Luminor Hôtel de Ville',
      address: '20 Rue du Temple, 75004 Paris',
      lat: 48.8572,
      lng: 2.3575,
      website: 'https://www.luminor-hoteldeville.com',
      district: '4e arrondissement',
    },
    {
      id: 'C0139',
      name: 'Majestic Bastille',
      address: '4 Boulevard Richard Lenoir, 75011 Paris',
      lat: 48.8528,
      lng: 2.3706,
      website: 'https://www.dulaccinemas.com/cinema/2851/majestic-bastille/portail',
      district: '11e arrondissement',
    },
    {
      id: 'C0120',
      name: 'Majestic Passy',
      address: '18 Avenue de la Muette, 75016 Paris',
      lat: 48.8575,
      lng: 2.2803,
      website: 'https://www.dulaccinemas.com/cinema/2853/majestic-passy/portail',
      district: '16e arrondissement',
    },
    {
      id: 'C0089',
      name: 'Max Linder Panorama',
      address: '24 Boulevard Poissonnière, 75009 Paris',
      lat: 48.8722,
      lng: 2.3442,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/max-linder-panorama',
      district: '9e arrondissement',
    },
    {
      id: 'C0041',
      name: 'Nouvel Odéon',
      address: '6 Rue de l\'École de Médecine, 75006 Paris',
      lat: 48.8514,
      lng: 2.3408,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/nouvel-odeon',
      district: '6e arrondissement',
    },
    {
      id: 'C0074',
      name: 'Reflet Médicis',
      address: '3 Rue Champollion, 75005 Paris',
      lat: 48.8492,
      lng: 2.3431,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/reflet-medicis',
      district: '5e arrondissement',
    },
    {
      id: 'C0100',
      name: 'Saint-André-des-Arts',
      address: '30 Rue Saint-André-des-Arts, 75006 Paris',
      lat: 48.8536,
      lng: 2.3389,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/saint-andre-des-arts',
      district: '6e arrondissement',
    },
    {
      id: 'C0025',
      name: 'Sept Parnassiens',
      address: '98 Boulevard du Montparnasse, 75014 Paris',
      lat: 48.8422,
      lng: 2.3281,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/sept-parnassiens',
      district: '14e arrondissement',
    },
    {
      id: 'C0061',
      name: 'Studio 28',
      address: '10 Rue Tholozé, 75018 Paris',
      lat: 48.8847,
      lng: 2.3369,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/studio-28',
      district: '18e arrondissement',
    },
    {
      id: 'C0083',
      name: 'Studio des Ursulines',
      address: '10 Rue des Ursulines, 75005 Paris',
      lat: 48.8447,
      lng: 2.3456,
      website: 'http://www.studiodesursulines.com',
      district: '5e arrondissement',
    },
    {
      id: 'C0016',
      name: 'Studio Galande',
      address: '42 Rue de la Galande, 75005 Paris',
      lat: 48.8522,
      lng: 2.3464,
      website: 'https://www.studiogalande.fr',
      district: '5e arrondissement',
    },
    {
      id: 'C0095',
      name: 'Les 3 Luxembourg',
      address: '67 Rue Monsieur-le-Prince, 75006 Paris',
      lat: 48.8497,
      lng: 2.3381,
      website: 'https://www.lestroisluxembourg.com',
      district: '6e arrondissement',
    },
    {
      id: 'W7588',
      name: 'Jeu de Paume',
      address: '1 Place de la Concorde, 75001 Paris',
      lat: 48.8656,
      lng: 2.3214,
      website: 'https://jeudepaume.org',
      district: '1er arrondissement',
    },
    {
      id: 'C0108',
      name: 'Les Elysées Lincoln',
      address: '14 Rue Lincoln, 75008 Paris',
      lat: 48.8703,
      lng: 2.3008,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/les-elysees-lincoln',
      district: '8e arrondissement',
    },
    {
      id: 'C0004',
      name: 'Cinéma des Cinéastes',
      address: '7 Avenue de Clichy, 75017 Paris',
      lat: 48.8842,
      lng: 2.3269,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/cinema-des-cineastes',
      district: '17e arrondissement',
    },
    {
      id: 'W7517',
      name: "Club de l'Étoile",
      address: '14 Rue Troyon, 75017 Paris',
      lat: 48.8756,
      lng: 2.2903,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/club-de-letoile',
      district: '17e arrondissement',
    },
    {
      id: 'C0012',
      name: 'Les 5 Caumartin',
      address: '101 Rue Saint-Lazare, 75009 Paris',
      lat: 48.8736,
      lng: 2.3281,
      website: 'https://www.cinemasindependantsparisiens.fr/salle/les-5-caumartin',
      district: '9e arrondissement',
    },
  ],
  toulouse: [
    {
      id: 'P0071',
      name: 'ABC',
      address: '13 Rue Saint-Bernard, 31000 Toulouse',
      lat: 43.6007,
      lng: 1.4442,
      website: 'https://www.cinema-abc.fr',
    },
    {
      id: 'P0235',
      name: 'American Cosmograph',
      address: '24 Rue Montardy, 31000 Toulouse',
      lat: 43.6001,
      lng: 1.4448,
      website: 'https://www.americancosmograph.com',
    },
    {
      id: 'W3120',
      name: 'Utopia Borderouge',
      address: '24 Avenue de Fronton, 31200 Toulouse',
      lat: 43.6417,
      lng: 1.4208,
      website: 'https://www.cinemas-utopia.org/toulouse',
    },
    {
      id: 'P0056',
      name: 'Le cratère',
      address: '99 Grande Rue Saint-Michel, 31400 Toulouse',
      lat: 43.5928,
      lng: 1.4503,
      website: 'https://www.lecratere.fr',
    },
    {
      id: 'P0057',
      name: 'Pathé Wilson',
      address: '3 Place du Président Thomas Wilson, 31000 Toulouse',
      lat: 43.6045,
      lng: 1.4444,
      website: 'https://www.cinemaspathegaumont.com/cinema/cinema-pathe-wilson',
    },
    {
      id: 'W3140',
      name: 'UGC Montaudran',
      address: '1 Avenue de la Gloire, 31400 Toulouse',
      lat: 43.5708,
      lng: 1.4714,
      website: 'https://www.ugc.fr/cinema.html?id=3140',
    },
  ],
};

/**
 * Get Google Maps directions URL
 */
export function getGoogleMapsDirectionsUrl(address: string): string {
  const encodedAddress = encodeURIComponent(address);
  return `https://www.google.com/maps/dir/?api=1&destination=${encodedAddress}`;
}

/**
 * Get Google Maps place URL
 */
export function getGoogleMapsPlaceUrl(address: string): string {
  const encodedAddress = encodeURIComponent(address);
  return `https://www.google.com/maps/search/?api=1&query=${encodedAddress}`;
}
